<?php if (DEBUG_MODE)var_dump($video) ?>

<?php if (!empty($message)): ?>
    <p class="message"><?= $message ?></p>
<?php else : ?>
    <?php /*
    <h1><?= $video->snippet->title ?></h1>
    <iframe
            id="player"
            class="<?= $video->format ?>"
            width="<?= $video->width ?>"
            height="<?= $video->height ?>"
            src="https://www.youtube.com/embed/<?= $video->id ?><?= $video->options ?>"
            frameborder="0"
            allowfullscreen>
    </iframe>
    <p><?= nl2br($video->snippet->description) ?></p>
    <p><img src="<?= $video->snippet->thumbnails['default']['url'] ?>" ?></p>

*/ ?>

    <h1><?= $video->title ?></h1>
    <iframe
            id="player"
            class="<?= $video->format ?>"
            width="<?= $video->width ?>"
            height="<?= $video->height ?>"
            src="https://www.youtube.com/embed/<?= $video->reference ?><?= $video->options ?>"
            frameborder="0"
            allowfullscreen>
    </iframe>


<?php endif ?>