<?php if (!empty($message)): ?>
    <p class="message"><?= $message ?></p>
<?php else : ?>

    <h1><?= $video->title ?></h1>
    <iframe
            id="player"
            class="<?= $video->format ?>"
            width="<?= $video->width ?>"
            height="<?= $video->height ?>"
            src="https://www.youtube.com/embed/<?= $video->reference ?><?= $video->options ?>"
            frameborder="0"
            allowfullscreen>
    </iframe>

<?php endif ?>
